name: Generate Podcast Feeds
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Podcast RSS Generator
        uses: regmi2/podcast-rss-generator@main
        
    
